apiVersion: v1
kind: Namespace
metadata:
  name: pixie-query
  labels:
    name: pixie-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixie-server
  namespace: pixie-query
  labels:
    app: pixie-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixie-server
  template:
    metadata:
      labels:
        app: pixie-server
    spec:
      hostAliases:
        - ip: "192.168.209.62"
          hostnames:
            - "dev.withpixie.dev"
            - "work.dev.withpixie.dev"
      containers:
        - name: pixie-server
          image: pixie-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pixie-config
                  key: px_api_key
            - name: PX_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: pixie-config
                  key: px_cluster_id
            - name: CLOUD_ADDR
              valueFrom:
                secretKeyRef:
                  name: pixie-config
                  key: cloud_addr
---
apiVersion: v1
kind: Service
metadata:
  name: pixie-server
  namespace: pixie-query
  labels:
    app: pixie-server
spec:
  selector:
    app: pixie-server
  ports:
    - protocol: TCP
      port: 8080          # ClusterIP port
      targetPort: 8080
  type: NodePort         # Expose externally via node port
